# Generated by Django 3.1.7 on 2021-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='shipping_rate_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
