# Generated by Django 3.1.7 on 2021-03-19 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210319_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbillingaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userbillingaddress',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='usermailingaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermailingaddress',
            name='last_name',
        ),
    ]
