# Generated by Django 3.1.7 on 2021-03-20 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_billing_address'),
        ('accounts', '0008_auto_20210320_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstripe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermailingaddress',
            name='use_billing_address',
        ),
        migrations.DeleteModel(
            name='UserBillingAddress',
        ),
        migrations.DeleteModel(
            name='UserStripe',
        ),
    ]
