# Generated by Django 3.1.7 on 2021-03-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20160127_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='height',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='length',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productvariation',
            name='width',
            field=models.IntegerField(default=32),
            preserve_default=False,
        ),
    ]
